[framework]
name = "alpaca"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "micro"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore"
